### ISSUE TITLE
KeyError: 'PUNCTSIDE_FIN' While running the "Distant Supervision (Heuristic)" and "Distant Supervision (COMET)"

### ISSUE THREAD

**Issue by krigeta** [skgabriel/paracomet#3]
Hello , i am setting up a colab for this and when I try to run [Distant Supervision (Heuristic)](https://github.com/skgabriel/paracomet#distant-supervision-heuristic) and [Distant Supervision (COMET)](https://github.com/skgabriel/paracomet#distant-supervision-comet)

```
INFO:transformers.modeling_utils:loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-pytorch_model.bin from cache at /root/.cache/torch/transformers/4295d67f022061768f4adc386234dbdb781c814c39662dd1662221c309962c55.778cf36f5c4e5d94c8cd9cefcf2a580c8643570eb327f0d4a1f007fab2acbdf1
INFO:transformers.modeling_utils:Weights of GPT2LMHeadModel not initialized from pretrained model: ['lm_head.weight']
INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-vocab.json from cache at /root/.cache/torch/transformers/f2808208f9bec2320371a9f5f891c184ae0b674ef866b79c58177067d15732dd.1512018be4ba4e8726e41b9145129dc30651ea4fec86aa61f4b9f40bf94eac71
INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-merges.txt from cache at /root/.cache/torch/transformers/d629f792e430b3c76a1291bb2766b0a047e36fae0588f9dbc1ae51decdff691b.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
Traceback (most recent call last):
  File "distant_supervision.py", line 32, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/usr/local/lib/python3.7/dist-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 135, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.7/dist-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.7/dist-packages/spacy/language.py", line 643, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 643, in spacy.pipeline.Tagger.from_disk
  File "/usr/local/lib/python3.7/dist-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 632, in spacy.pipeline.Tagger.from_disk.load_tag_map
  File "morphology.pyx", line 56, in spacy.morphology.Morphology.__init__
  File "attrs.pyx", line 147, in spacy.attrs.intify_attrs
**KeyError: 'PUNCTSIDE_FIN'**
```

And do I have to run both of them ([Distant Supervision (Heuristic)](https://github.com/skgabriel/paracomet#distant-supervision-heuristic) and [Distant Supervision (COMET)](https://github.com/skgabriel/paracomet#distant-supervision-comet)) or which one is better for longer input?

**Comment by skgabriel** [comment]
You can try both, but the COMET distant supervision may be more on-topic for longer inputs. For the error above, I haven't seen that before running the code, but it looks like a spacy version mismatch issue so I would try another version.
